/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 pudding.gltf 
Author: Citrus (https://sketchfab.com/citrusfriendd)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-pudding-2fe0451867b5422980b02064ed3efdb0
Title: Japanese Pudding
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pudding.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0.546, 0.407, 1.214]} rotation={[2.816, -0.73, 2.891]} scale={[0.004, 0, 0.003]}>
        <mesh geometry={nodes.Spoon_lambert1_0.geometry} material={materials.lambert1} />
        <mesh geometry={nodes.SpoonBottom_lambert1_0.geometry} material={materials.lambert1} position={[-287.87, 2.478, -11.201]} rotation={[0, 0, -Math.PI / 2]} scale={[1.363, 2.014, 0.583]} />
      </group>
      <mesh geometry={nodes.Plate_lambert1_0.geometry} material={materials.lambert1} position={[0, 0.115, 0]} scale={[0.015, 0.001, 0.015]} />
      <mesh geometry={nodes.Pudding_lambert1_0.geometry} material={materials.lambert1} position={[0, 1.034, 0]} scale={[0.011, 0.01, 0.011]} />
    </group>
  )
}

useGLTF.preload('/pudding.gltf')
