/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 bee.gltf 
Author: Hasksoft (https://sketchfab.com/Hasksoft)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/smol-ame-bee-add6975128c24b5dabbf475b9fed797b
Title: Smol Ame bee
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Bee(props) {
  const { nodes, materials } = useGLTF('/bee.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <group rotation={[-Math.PI / 2, 0, 0]} scale={48.298}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.AmeBee} skeleton={nodes.Object_7.skeleton} />
          <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.AmeBee} skeleton={nodes.Object_9.skeleton} />
          <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.AmeBeeNoShader} skeleton={nodes.Object_11.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bee.gltf')
