/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 src/honey_bear_bottle/honeybear.gltf 
Author: Batuhan13 (https://sketchfab.com/Batuhan13)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/honey-bear-bottle-6f4c1566b9674a208d618b4a00d0343c
Title: Honey bear bottle
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function HoneyBear(props) {
  const { nodes, materials } = useGLTF('/honeybear.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.defaultMaterial.geometry} material={materials.Material_001} />
          <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.Plane_002} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/honeybear.gltf')
