/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 cup-of-drink.glb
Author: operkhalskam (https://www.cgtrader.com/operkhalskam)
License: Royalty Free License
Source: https://www.cgtrader.com/3d-models/food/beverage/bubble-tea-drink
Title: Bubble tea drink 3D model
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { MeshBasicMaterial } from 'three';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF('/cup-of-drink.glb')

  // Set transparency and opacity for the cup material
  materials['Plastic Glass Shader'].transparent = true;
  materials['Plastic Glass Shader'].opacity = 0.05;

  // Set transparency for the drink material
  materials['Plastic.001'].transparent = true;

  // Set transparency for cube material
  materials['Ice.001'].transparent = true;
  materials['Ice.002'].transparent = true;
  materials['Ice.003'].transparent = true;

  // Create a new material for the tube with a blue color
  const tubeMaterial = new MeshBasicMaterial({ color: 'cornflowerblue' });

  // TODO: Maybe add some shaders?
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={[2.257, 5.702, 1.711]}>
        <mesh geometry={nodes.Cap.geometry} material={materials['Plastic Glass Shader']} position={[0, 0.628, 0]} scale={[0.625, 0.247, 0.824]} />
        <mesh geometry={nodes.Cup.geometry} material={materials['Plastic Glass Shader']} scale={[0.443, 0.175, 0.584]} />
        <mesh geometry={nodes.Ice_cube.geometry} material={materials.Ice} position={[-0.333, 0.452, 0]} rotation={[0, 0, 0.635]} scale={[0.105, 0.081, 0.163]} />
        <mesh geometry={nodes.Ice_cube001.geometry} material={materials['Ice.001']} position={[-0.122, 0.356, -0.338]} rotation={[-0.265, -0.887, 0.419]} scale={[0.085, 0.065, 0.104]} />
        <mesh geometry={nodes.Ice_cube002.geometry} material={materials['Ice.002']} position={[0.325, 0.452, 0.242]} rotation={[-0.047, -1.306, -0.384]} scale={[0.153, 0.054, 0.123]} />
        <mesh geometry={nodes.Ice_cube003.geometry} material={materials['Ice.003']} position={[-0.332, 0.278, 0.298]} rotation={[2.217, -1.29, 2.876]} scale={[0.083, 0.062, 0.083]} />
        <mesh geometry={nodes.Liquid.geometry} material={materials['Plastic.001']} scale={[0.438, 0.173, 0.578]} />
        <mesh geometry={nodes.Sphere.geometry} material={materials.Bubbles} position={[-0.306, 0.113, 0]} scale={[0.067, 0.027, 0.089]} />
        <mesh geometry={nodes.Sphere001.geometry} material={materials.Bubbles} position={[-0.069, 0.156, -0.344]} scale={[0.055, 0.022, 0.072]} />
        <mesh geometry={nodes.Sphere002.geometry} material={materials.Bubbles} position={[0.301, 0.074, -0.123]} scale={[0.071, 0.028, 0.093]} />
        <mesh geometry={nodes.Sphere003.geometry} material={materials.Bubbles} position={[0.033, 0.093, 0.309]} scale={[0.064, 0.026, 0.085]} />
        <mesh geometry={nodes.Sphere004.geometry} material={materials.Bubbles} position={[-0.138, 0.082, 0.285]} scale={[0.065, 0.026, 0.086]} />
        <mesh geometry={nodes.Sphere005.geometry} material={materials.Bubbles} position={[0.109, 0.143, 0.466]} scale={[0.071, 0.028, 0.093]} />
        <mesh geometry={nodes.Sphere007.geometry} material={materials.Bubbles} position={[-0.306, 0.08, -0.151]} scale={[0.071, 0.028, 0.094]} />
        <mesh geometry={nodes.Sphere008.geometry} material={materials.Bubbles} position={[-0.058, 0.07, -0.224]} scale={[0.053, 0.021, 0.07]} />
        <mesh geometry={nodes.Sphere009.geometry} material={materials.Bubbles} position={[0.343, 0.109, 0.067]} scale={[0.075, 0.03, 0.099]} />
        <mesh geometry={nodes.Sphere010.geometry} material={materials.Bubbles} position={[0.16, 0.054, 0.337]} scale={[0.046, 0.018, 0.061]} />
        <mesh geometry={nodes.Sphere011.geometry} material={materials.Bubbles} position={[-0.282, 0.17, 0.215]} scale={[0.069, 0.027, 0.091]} />
        <mesh geometry={nodes.Sphere012.geometry} material={materials.Bubbles} position={[0.258, 0.154, -0.292]} scale={[0.075, 0.03, 0.099]} />
        <mesh geometry={nodes.Tube.geometry} material={tubeMaterial} position={[0.052, 0.604, -0.01]} rotation={[-1.649, 1.354, 1.803]} scale={[0.584, 0.186, 0.439]} />
      </group>
      {/* Add background */}
      {/* <mesh geometry={nodes.BG.geometry} material={materials.BG} position={[0, -0.02, 0]} scale={13.842} /> */}
      {/* Add lighting */}
      <ambientLight intensity={0.5} />
      <directionalLight intensity={1.2} position={[5, 10, 5]} />
    </group>
  )
}

useGLTF.preload('/cup-of-drink.glb')
