/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 beans.gltf 
Author: John Fino (tauricity) (https://sketchfab.com/tauricity)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-beans-autodesk-memento-031fd22dc6b943c09906b0a9f65fd199
Title: Coffee Beans- Autodesk Memento
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Beans(props) {
  const { nodes, materials } = useGLTF('/beans.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]} scale={0.007}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.Material_0} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.Material_0} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Material_0} />
      </group>
    </group>
  )
}

useGLTF.preload('/beans.gltf')
