/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 src/japanese_tsubuan_ohagi/redbean.gltf 
Author: 3DSPICE (https://sketchfab.com/3DSPICE)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-tsubuan-ohagi-3c70d72479844a56801150ff50f63c0c
Title: Japanese Tsubuan Ohagi（つぶあんおはぎ）
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function RedBeanPaste(props) {
  const { nodes, materials } = useGLTF('/redbean.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes['���������001_���������001_0'].geometry} material={materials['.001']} rotation={[0.472, 0.051, 0.126]} scale={300} />
      </group>
    </group>
  )
}

useGLTF.preload('/redbean.gltf')
